begin;
create table public.birdshop_services (
 slug text primary key check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
 data jsonb not null check(jsonb_typeof(data)='object'),
 packages jsonb not null default '[]' check(jsonb_typeof(packages)='array'),
 is_visible boolean not null default true,
 deleted_at timestamptz,
 updated_by uuid,
 updated_at timestamptz not null default now()
);
alter table public.birdshop_services enable row level security;
revoke all on public.birdshop_services from public,anon,authenticated;
grant select on public.birdshop_services to authenticated;
grant all on public.birdshop_services to service_role;
create policy owner_catalog_read on public.birdshop_services for select to authenticated using(public.is_birdshop_owner());

insert into public.birdshop_services(slug,data,packages) values ('deepwoken-progression','{"slug": "deepwoken-progression", "name": "Deepwoken Progression", "game": "Deepwoken", "category": "Progression", "initials": "DP", "shortDescription": "Custom progression assistance built around your character, goals, and preferred progression path.", "description": "A personalized Deepwoken progression service designed around your current character and progression goals.", "startingPrice": 14.99, "turnaround": "1\u20133 Days", "delivery": "Custom Service", "badge": "POPULAR", "featured": true, "available": true, "features": ["Custom progression goals", "Progress updates", "Private BirdShop chat", "Flexible service options"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('deepwoken-build-setup','{"slug": "deepwoken-build-setup", "name": "Deepwoken Build Setup", "game": "Deepwoken", "category": "Build Setup", "initials": "DB", "shortDescription": "Help preparing and progressing toward a specific Deepwoken build or character setup.", "description": "A build-focused Deepwoken service for customers working toward a particular character setup.", "startingPrice": 19.99, "turnaround": "1\u20134 Days", "delivery": "Custom Service", "badge": "FEATURED", "available": true, "features": ["Build-focused progression", "Goal planning", "Custom requirements", "BirdShop support"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('deepwoken-oath-preparation','{"slug": "deepwoken-oath-preparation", "name": "Deepwoken Oath Preparation", "game": "Deepwoken", "category": "Progression", "initials": "DO", "shortDescription": "Preparation assistance for players working toward a selected oath and its requirements.", "description": "A focused service for preparing the progression and requirements involved with your selected oath.", "startingPrice": 12.99, "turnaround": "1\u20133 Days", "delivery": "Custom Service", "available": true, "features": ["Requirement planning", "Progress guidance", "Goal tracking", "Custom requests"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('deepwoken-resource-run','{"slug": "deepwoken-resource-run", "name": "Deepwoken Resource Run", "game": "Deepwoken", "category": "Grinding", "initials": "DR", "shortDescription": "Assistance gathering selected resources and preparing for your next progression objective.", "description": "Resource-focused help based around the materials and progression objectives you currently need.", "startingPrice": 9.99, "turnaround": "1\u20132 Days", "delivery": "Custom Service", "available": true, "features": ["Selected resources", "Custom quantities", "Progress updates", "Flexible requests"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('deepwoken-new-character','{"slug": "deepwoken-new-character", "name": "Deepwoken New Character Start", "game": "Deepwoken", "category": "Progression", "initials": "DC", "shortDescription": "A clean starting service for setting up a new Deepwoken character and early progression path.", "description": "Designed for starting a new character with an organized progression direction from the beginning.", "startingPrice": 11.99, "turnaround": "1\u20132 Days", "delivery": "Custom Service", "available": true, "features": ["New character setup", "Early progression", "Build direction", "Goal planning"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('deepwoken-boss-preparation','{"slug": "deepwoken-boss-preparation", "name": "Deepwoken Boss Preparation", "game": "Deepwoken", "category": "Coaching", "initials": "BP", "shortDescription": "Prepare your build, strategy, and progression before taking on a difficult encounter.", "description": "A preparation-focused service for players wanting help getting ready for specific encounters.", "startingPrice": 8.99, "turnaround": "Same Day", "delivery": "Guided Service", "available": true, "features": ["Build review", "Preparation checklist", "Strategy assistance", "Discord guidance"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('bloxburg-house-build','{"slug": "bloxburg-house-build", "name": "Bloxburg House Building", "game": "Bloxburg", "category": "Building", "initials": "BH", "shortDescription": "Custom Bloxburg homes designed around your preferred style, budget, and property requirements.", "description": "A complete Bloxburg house-building service based around your references, style, and requirements.", "startingPrice": 24.99, "turnaround": "2\u20137 Days", "delivery": "Custom Build", "badge": "BEST SELLER", "featured": true, "available": true, "features": ["Custom house design", "Reference-based builds", "Room planning", "Exterior detailing"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('bloxburg-interior-design','{"slug": "bloxburg-interior-design", "name": "Bloxburg Interior Design", "game": "Bloxburg", "category": "Design", "initials": "BI", "shortDescription": "Interior redesigns and decorating for existing Bloxburg homes and custom builds.", "description": "Interior design focused on furnishing, layouts, decorating, and improving existing spaces.", "startingPrice": 12.99, "turnaround": "1\u20134 Days", "delivery": "Custom Build", "available": true, "features": ["Interior decorating", "Room redesign", "Furniture layouts", "Style matching"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('bloxburg-mansion-build','{"slug": "bloxburg-mansion-build", "name": "Bloxburg Mansion Build", "game": "Bloxburg", "category": "Building", "initials": "BM", "shortDescription": "Large-scale luxury home construction for more detailed and ambitious Bloxburg projects.", "description": "A larger custom-build option intended for detailed homes, estates, and luxury projects.", "startingPrice": 49.99, "turnaround": "4\u201310 Days", "delivery": "Large Custom Build", "badge": "PREMIUM", "available": true, "features": ["Large custom property", "Detailed floor plans", "Exterior design", "Interior planning"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('bloxburg-starter-home','{"slug": "bloxburg-starter-home", "name": "Bloxburg Starter Home", "game": "Bloxburg", "category": "Building", "initials": "BS", "shortDescription": "A polished smaller home for players wanting something affordable, clean, and complete.", "description": "A smaller custom home designed around practical budgets without losing BirdShop''s detailed design approach.", "startingPrice": 14.99, "turnaround": "1\u20133 Days", "delivery": "Custom Build", "available": true, "features": ["Smaller house design", "Budget conscious", "Interior included", "Fast turnaround"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('bloxburg-landscaping','{"slug": "bloxburg-landscaping", "name": "Bloxburg Landscaping", "game": "Bloxburg", "category": "Design", "initials": "BL", "shortDescription": "Upgrade the outside of your property with landscaping, paths, plants, and exterior detailing.", "description": "A focused landscaping service for improving the exterior presentation of an existing property.", "startingPrice": 9.99, "turnaround": "1\u20133 Days", "delivery": "Custom Design", "available": true, "features": ["Plant placement", "Path design", "Outdoor detailing", "Style matching"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('bloxburg-room-makeover','{"slug": "bloxburg-room-makeover", "name": "Bloxburg Room Makeover", "game": "Bloxburg", "category": "Design", "initials": "BR", "shortDescription": "Transform a single room or small area without rebuilding your entire Bloxburg property.", "description": "A smaller interior-design option for individual rooms and focused home improvements.", "startingPrice": 7.99, "turnaround": "Same Day\u20132 Days", "delivery": "Custom Design", "available": true, "features": ["Single-room redesign", "Furniture planning", "Theme matching", "Smaller projects"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('roblox-obby-coaching','{"slug": "roblox-obby-coaching", "name": "Roblox Obby Coaching", "game": "Roblox", "category": "Coaching", "initials": "RO", "shortDescription": "One-on-one help improving movement, timing, and consistency across difficult obstacle courses.", "description": "A guided coaching service focused on helping players improve movement and obstacle-course consistency.", "startingPrice": 8.99, "turnaround": "Scheduled Session", "delivery": "Guided Service", "available": true, "features": ["Movement guidance", "Practice sessions", "Technique review", "Private BirdShop chat"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('roblox-progression-help','{"slug": "roblox-progression-help", "name": "Roblox Game Progression", "game": "Roblox", "category": "Progression", "initials": "RP", "shortDescription": "Flexible progression assistance for supported Roblox games and specific player goals.", "description": "A general Roblox progression option for supported games that do not have their own dedicated BirdShop listing.", "startingPrice": 11.99, "turnaround": "1\u20134 Days", "delivery": "Custom Service", "available": true, "features": ["Multiple supported games", "Goal-based service", "Custom scope", "Progress updates"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('roblox-custom-task','{"slug": "roblox-custom-task", "name": "Roblox Custom Task", "game": "Roblox", "category": "Custom", "initials": "RT", "shortDescription": "Request a specific supported Roblox task that does not fit one of the standard service listings.", "description": "A flexible Roblox service for custom requests, unusual tasks, or game-specific requirements.", "startingPrice": null, "turnaround": "Varies", "delivery": "Custom Quote", "available": true, "features": ["Custom requirements", "Game-specific requests", "Quote before starting", "Private consultation"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('minecraft-starter-base','{"slug": "minecraft-starter-base", "name": "Minecraft Starter Base", "game": "Minecraft", "category": "Building", "initials": "MS", "shortDescription": "A complete starter base designed around your world, preferred style, and available space.", "description": "A practical Minecraft base-building service for players wanting a polished early-game home.", "startingPrice": 14.99, "turnaround": "1\u20133 Days", "delivery": "Custom Build", "available": true, "features": ["Custom starter base", "Storage layout", "Interior setup", "Style selection"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('minecraft-mega-base','{"slug": "minecraft-mega-base", "name": "Minecraft Mega Base", "game": "Minecraft", "category": "Building", "initials": "MM", "shortDescription": "Large custom Minecraft structures for ambitious survival and creative-world projects.", "description": "A large-scale Minecraft building option designed for detailed and ambitious projects.", "startingPrice": 44.99, "turnaround": "4\u201310 Days", "delivery": "Large Custom Build", "badge": "PREMIUM", "available": true, "features": ["Large-scale builds", "Custom themes", "Interior planning", "Detailed structures"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('minecraft-resource-gathering','{"slug": "minecraft-resource-gathering", "name": "Minecraft Resource Gathering", "game": "Minecraft", "category": "Grinding", "initials": "MR", "shortDescription": "Resource-focused assistance for players preparing to build, craft, or expand their world.", "description": "A flexible resource-oriented service based on the materials required for your next Minecraft goal.", "startingPrice": 9.99, "turnaround": "1\u20133 Days", "delivery": "Custom Service", "available": true, "features": ["Selected resources", "Custom quantities", "Goal-based requests", "Progress updates"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('minecraft-redstone-setup','{"slug": "minecraft-redstone-setup", "name": "Minecraft Redstone Setup", "game": "Minecraft", "category": "Build Setup", "initials": "RS", "shortDescription": "Help designing and setting up practical Redstone systems for your Minecraft builds.", "description": "A technical build service for supported Redstone systems, mechanisms, and practical automation.", "startingPrice": 12.99, "turnaround": "1\u20134 Days", "delivery": "Technical Build", "available": true, "features": ["Redstone planning", "System setup", "Troubleshooting", "Custom mechanisms"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('gta-heist-preparation','{"slug": "gta-heist-preparation", "name": "GTA V Heist Preparation", "game": "GTA V", "category": "Coaching", "initials": "GH", "shortDescription": "Preparation and strategy help for players organizing supported GTA Online heist content.", "description": "A coaching and preparation service focused on planning routes, roles, and approaches.", "startingPrice": 9.99, "turnaround": "Scheduled Session", "delivery": "Guided Service", "available": true, "features": ["Preparation planning", "Role discussion", "Strategy assistance", "Discord guidance"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('gta-vehicle-setup','{"slug": "gta-vehicle-setup", "name": "GTA V Vehicle Setup Guide", "game": "GTA V", "category": "Build Setup", "initials": "GV", "shortDescription": "Help planning vehicle selections, customization direction, and garage organization.", "description": "A guided GTA Online service focused on vehicle planning and customization direction.", "startingPrice": 7.99, "turnaround": "Same Day", "delivery": "Guided Service", "available": true, "features": ["Vehicle recommendations", "Garage planning", "Customization ideas", "Budget planning"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('fortnite-coaching','{"slug": "fortnite-coaching", "name": "Fortnite Coaching", "game": "Fortnite", "category": "Coaching", "initials": "FC", "shortDescription": "Personal gameplay coaching focused on decision-making, mechanics, and overall consistency.", "description": "A guided coaching session built around the areas of Fortnite you specifically want to improve.", "startingPrice": 12.99, "turnaround": "Scheduled Session", "delivery": "Coaching Session", "available": true, "features": ["Gameplay review", "Decision-making", "Mechanical practice", "Personal feedback"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('fortnite-build-edit-coaching','{"slug": "fortnite-build-edit-coaching", "name": "Fortnite Build & Edit Coaching", "game": "Fortnite", "category": "Coaching", "initials": "FE", "shortDescription": "Focused practice for building, editing, movement, and mechanical consistency.", "description": "A mechanics-focused Fortnite coaching option for players wanting targeted build and edit practice.", "startingPrice": 9.99, "turnaround": "Scheduled Session", "delivery": "Coaching Session", "available": true, "features": ["Build practice", "Edit practice", "Movement review", "Training routines"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('custom-game-service','{"slug": "custom-game-service", "name": "Custom Game Service", "game": "Multi-Game", "category": "Custom", "initials": "CG", "shortDescription": "Have something specific in mind? Request a personalized game service directly through BirdShop.", "description": "A flexible service option for requests that do not fit one of BirdShop''s standard listings.", "startingPrice": null, "turnaround": "Varies", "delivery": "Custom Quote", "badge": "CUSTOM", "featured": true, "available": true, "features": ["Custom requests", "Multiple supported games", "Quote before purchase", "Private consultation"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
insert into public.birdshop_services(slug,data,packages) values ('custom-build-request','{"slug": "custom-build-request", "name": "Custom Build Request", "game": "Multi-Game", "category": "Custom", "initials": "CB", "shortDescription": "Send references and requirements for a completely custom building or design request.", "description": "A flexible custom-build option for larger or unusual projects requiring a personalized quote.", "startingPrice": null, "turnaround": "Varies", "delivery": "Custom Quote", "available": true, "features": ["Reference images", "Custom scope", "Personalized quote", "Large projects"]}'::jsonb,'[{"id": "starter", "name": "Basic", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "standard", "name": "Standard", "enabled": false, "cents": null, "scope": "", "includes": []}, {"id": "premium", "name": "Premium", "enabled": false, "cents": null, "scope": "", "includes": []}]'::jsonb);
create table public.birdshop_service_purchases (
 request_id uuid primary key,
 fingerprint jsonb not null,
 conversation_id uuid not null references public.service_conversations(id) on delete restrict,
 payment_request_id uuid not null unique references public.service_payment_requests(id) on delete restrict,
 created_at timestamptz not null default now()
);
alter table public.birdshop_service_purchases enable row level security;
revoke all on public.birdshop_service_purchases from public,anon,authenticated;
grant all on public.birdshop_service_purchases to service_role;
create function public.birdshop_buy_service_package(p_request_id uuid,p_slug text,p_tier text,p_name text,p_email text,p_expected_cents bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare s public.birdshop_services%rowtype; pack jsonb; existing public.birdshop_service_purchases%rowtype;
 c jsonb; payment_id uuid; fingerprint jsonb; token text;
begin
 perform private.birdshop_require_server();
 if p_request_id is null or p_tier not in ('starter','standard','premium') or length(trim(p_name)) not between 2 and 100 or length(p_email)>320 or p_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception 'Invalid request.'; end if;
 fingerprint:=jsonb_build_object('slug',p_slug,'tier',p_tier,'name',trim(p_name),'email',lower(trim(p_email)),'cents',p_expected_cents);
 perform pg_advisory_xact_lock(hashtextextended(p_request_id::text,9));
 select * into existing from public.birdshop_service_purchases where request_id=p_request_id;
 if found then
  if existing.fingerprint<>fingerprint then raise exception 'Request changed. Start a new purchase.'; end if;
  select public_token into token from public.service_conversations where id=existing.conversation_id and deleted_at is null;
  if token is null then raise exception 'Conversation unavailable.'; end if;
  return jsonb_build_object('public_token',token,'payment_request_id',existing.payment_request_id);
 end if;
 select * into s from public.birdshop_services where slug=p_slug and is_visible and deleted_at is null for share;
 if not found or not coalesce((s.data->>'available')::boolean,false) then raise exception 'Service unavailable.'; end if;
 select x into pack from jsonb_array_elements(s.packages) x where x->>'id'=p_tier and x->>'enabled'='true';
 if pack is null or (pack->>'cents')::bigint not between 50 and 99999999 or length(trim(pack->>'scope'))<5 then raise exception 'Package unavailable.'; end if;
 if p_expected_cents is null or p_expected_cents<>(pack->>'cents')::bigint then raise exception 'Package price changed. Refresh before purchasing.'; end if;
 c:=public.birdshop_create_conversation('service',trim(p_name),lower(trim(p_email)),null,
 left(s.data->>'name'||' — '||(pack->>'name'),180),
 'Selected '||(pack->>'name')||': '||(pack->>'scope')||E'\nIncluded: '||coalesce((select string_agg(value,E'\n') from jsonb_array_elements_text(pack->'includes')),''),
 p_slug,s.data->>'name',p_tier,pack->>'name',null,null,null,null);
 update public.service_conversations set package_id=p_tier,package_name=pack->>'name' where id=(c->>'conversation_id')::uuid;
 insert into public.service_payment_requests(conversation_id,amount,currency,title,description,status,previous_workflow_status)
 values((c->>'conversation_id')::uuid,(pack->>'cents')::numeric/100,'usd',left(s.data->>'name'||' — '||(pack->>'name'),180),
 left((pack->>'scope')||E'\n'||coalesce((select string_agg(value,E'\n') from jsonb_array_elements_text(pack->'includes')),''),2000),'pending',
 (select workflow_status from public.service_conversations where id=(c->>'conversation_id')::uuid)) returning id into payment_id;
 insert into public.birdshop_service_purchases(request_id,fingerprint,conversation_id,payment_request_id) values(p_request_id,fingerprint,(c->>'conversation_id')::uuid,payment_id);
 insert into public.service_messages(conversation_id,sender_type,sender_label,body)
 values((c->>'conversation_id')::uuid,'system','BirdShop','Your package is selected. Once payment is confirmed, use this private chat to share your requirements and arrange the next steps.');
 return jsonb_build_object('public_token',c->>'public_token','payment_request_id',payment_id);
end $$;
revoke all on function public.birdshop_buy_service_package(uuid,text,text,text,text,bigint) from public,anon,authenticated;
grant execute on function public.birdshop_buy_service_package(uuid,text,text,text,text,bigint) to service_role;
create function private.birdshop_service_catalog_audit() returns trigger language plpgsql security definer set search_path='' as $$
begin
 insert into public.birdshop_audit_log(actor_id,action,details) values(new.updated_by,
 case when new.deleted_at is not null then 'service_removed' when tg_op='INSERT' then 'service_created' else 'service_updated' end,
 jsonb_build_object('slug',new.slug,'visible',new.is_visible));
 return new;
end $$;
revoke all on function private.birdshop_service_catalog_audit() from public,anon,authenticated;
create trigger service_catalog_audit after insert or update on public.birdshop_services for each row execute function private.birdshop_service_catalog_audit();
notify pgrst,'reload schema';
commit;
